# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61i.proto\x12\x02\x61i\"a\n\rGeminiRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x18\n\x10previous_context\x18\x02 \x01(\t\x12\x15\n\rresponse_type\x18\x03 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x04 \x01(\t\"w\n\x0cTopicRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x15\n\rtopic_content\x18\x02 \x01(\t\x12\x18\n\x10previous_context\x18\x03 \x01(\t\x12\x15\n\rresponse_type\x18\x04 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x05 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\t2m\n\tAIService\x12\x30\n\rExplainGemini\x12\x11.ai.GeminiRequest\x1a\x0c.ai.Response\x12.\n\x0c\x45xplainTopic\x12\x10.ai.TopicRequest\x1a\x0c.ai.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GEMINIREQUEST']._serialized_start=16
  _globals['_GEMINIREQUEST']._serialized_end=113
  _globals['_TOPICREQUEST']._serialized_start=115
  _globals['_TOPICREQUEST']._serialized_end=234
  _globals['_RESPONSE']._serialized_start=236
  _globals['_RESPONSE']._serialized_end=262
  _globals['_AISERVICE']._serialized_start=264
  _globals['_AISERVICE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
